---
- name: Reboot server
  hosts: srv
  roles:
    - reboot

  vars_prompt:
    - name: "reboot"
      prompt: "Are you sure you want to reboot server (yes/no)?"
      private: no
      default: "no"
