---
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  changed_when: true
  when: reboot == "yes"

- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ hostname }}
      port={{ port }}
      state=started
      delay=10
      timeout=60
      connect_timeout=15
  become: false
  when: reboot == "yes"